
" BEGIN pget managed block
set runtimepath+=/opt/pget/plugin/vim-gnupg

set nobackup
set nowritebackup
set noswapfile
set noundofile
set viminfo=

let g:GPGPreferSymmetric = 1
let g:GPGCipher = 'AES256'
let g:GPGQuiet = 1
" END pget managed block

